### ISSUE TITLE
Clicking Build a Chart does nothing

### ISSUE THREAD

**Issue by plitwin** [OCTRI/REDCap-Vizr#63]
We are currently using Vizr 1.2.4+c7f2f316ed on REDCap version 8.8.2. This is on an existing project that already has some charts built. Both REDCap and Vizr were recently upgraded. The Build a Chart button no longer works. Clicking it does nothing.

**Comment by heathharrelson** [comment]
Updates in REDCap 8.7 required adjustments to Vizr, which are incorporated in the most recent releases ([2.2.0](https://github.com/OCTRI/REDCap-Vizr/releases/tag/v2.2.0) and [2.2.1](https://github.com/OCTRI/REDCap-Vizr/releases/tag/v2.2.1)). If you're using Vizr 1.2.4, you'll need to upgrade to 2.2.1. If you already upgraded to 2.2.1, it's possible you need to clear your browser cache.

**Comment by heathharrelson** [comment]
It just occurred to me that Vizr 1.2.4 is the old plugin version of Vizr (we migrated it to an external module with version 2.0.0). Is it possible you're clicking an old project bookmark that still uses the plugin?

**Comment by heathharrelson** [comment]
Verified that as expected Vizr 1.2.5 is not working with REDCap 8.9.0. The behavior is as described in this issue: Clicking the button to create a new chart bounces the page briefly, but the form never displays. No errors are logged to the console. This is most likely due to the switch to jQuery 3 or possibly structural changes related to Bootstrap 4 breaking our CSS selectors.

I have [updated README.md](https://github.com/OCTRI/REDCap-Vizr/pull/65) in the plugin branch and [released version 1.2.6](https://github.com/OCTRI/REDCap-Vizr/releases/tag/v1.2.6) noting that the plugin is superseded by the Vizr External Module.
